// components/home/styles.ts

import { StyleSheet, Dimensions } from 'react-native';
import { Palette } from '../../constants/Styles';

const { width } = Dimensions.get('window');

const SIDEBAR_WIDTH = width * 0.75;

export const styles = StyleSheet.create({
  // paste your existing localStyles here
  
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    marginBottom: 16,
  },
  greetingSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  actionsSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  iconBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: Palette.surfaceWhite,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Palette.borderSubtle,
  },
  profileBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: Palette.surfaceBlueMuted,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Palette.borderActiveBlue,
  },
  greetingTextContainer: {
    justifyContent: 'center',
  },
  userName: {
    fontSize: 18,
    fontWeight: '700',
    color: Palette.textPrimary,
  },
  notificationBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Palette.crimson,
  },
  contentContainer: {
    flex: 1,
    paddingTop: 8,
  },
  cycleCardContainer: {
    backgroundColor: Palette.surfaceElevated,
    borderRadius: 24,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Palette.borderSubtle,
  },
  cardHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  phaseTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  moonBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: 'center',
    alignItems: 'center',
  },
  phaseTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: Palette.textPrimary,
  },
  wheelContainer: {
    width: 160,
    height: 160,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 12,
  },
  wheelTextContainer: {
    position: 'absolute',
    alignItems: 'center',
  },
  percentageText: {
    fontSize: 28,
    fontWeight: '800',
    color: Palette.textPrimary,
  },
  statusText: {
    fontSize: 13,
    fontWeight: '700',
    marginTop: 2,
  },
  tagsContainer: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  pillTag: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  pillTagText: {
    fontSize: 13,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sidebarContainer: {
    width: SIDEBAR_WIDTH,
    height: '100%',
    backgroundColor: Palette.creamLight,
    padding: 24,
    justifyContent: 'space-between',
  },
  sidebarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
  },
  menuItems: {
    gap: 8,
    flex: 1,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  menuText: {
    fontSize: 16,
    fontWeight: '600',
    color: Palette.textPrimary,
  },
  logoutBtn: {
    marginTop: 'auto',
    marginBottom: 20,
  },
  reframeHeader: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
    paddingRight: 20,
  },
  reframeText: {
    fontSize: 14,
    color: Palette.textPrimary,
    lineHeight: 22,
    flexShrink: 1,
  },
  primaryPathBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
  },
  pathLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.7)',
    letterSpacing: 1,
    marginBottom: 4,
  },
  pathTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Palette.surfaceWhite,
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Palette.borderSubtle,
  },
  toggleTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: Palette.textPrimary,
    marginBottom: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 16,
    marginTop: 8,
  },
  recipeScroll: {
    marginHorizontal: -16,
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  recipeCard: {
    backgroundColor: Palette.surfaceWhite,
    borderRadius: 20,
    padding: 16,
    width: 240,
    marginRight: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  recipeIconBg: {
    backgroundColor: Palette.surfaceGreenMuted,
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  recipeTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Palette.textPrimary,
    marginBottom: 12,
    lineHeight: 22,
  },
  recipeTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  mindsetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  expandIcon: {
    backgroundColor: Palette.surfaceCrimsonMuted,
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mindsetContent: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: Palette.borderSubtle,
  },
  mindsetItem: {
    flexDirection: 'row',
    gap: 12,
  },
  verticalLine: {
    width: 3,
    backgroundColor: Palette.borderStrong,
    borderRadius: 2,
  },
  mindsetItemTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: Palette.textPrimary,
    marginBottom: 4,
  },
  trendHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  mockChartArea: {
    height: 80,
    backgroundColor: Palette.surfaceSubtle,
    borderRadius: 12,
    marginBottom: 16,
    overflow: 'hidden',
  },
  chartLegend: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  recipeModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  recipeModalContainer: {
    backgroundColor: Palette.creamLight,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    height: '85%',
  },
  recipeModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  closeBtnModal: {
    width: 40,
    height: 40,
    backgroundColor: Palette.surfaceWhite,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Palette.borderSubtle,
  },
  macroRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
  },
  macroBox: {
    backgroundColor: Palette.surfaceMuted,
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 4,
  },
  macroVal: {
    fontSize: 16,
    fontWeight: '800',
    color: Palette.textPrimary,
  },
  macroLabel: {
    fontSize: 11,
    color: Palette.textSecondary,
    marginTop: 2,
  },
  instructionSection: {
    backgroundColor: Palette.surfaceWhite,
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  instructionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Palette.textPrimary,
  },
  bulletText: {
    fontSize: 15,
    color: Palette.textPrimary,
    lineHeight: 24,
    marginBottom: 10,
  },

});